'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { useAppDispatch } from '@/store';
import { setCredentials } from '@/store/slices/authSlice';
import authService from '@/services/authService';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { AlertBanner } from '@/components/feedback/AlertBanner';
import { GuestGuard } from '@/components/auth/GuestGuard';
import { ShieldCheck, KeyRound, ArrowLeft, Clock, RefreshCw } from 'lucide-react';

const twoFactorSchema = z.object({
  code: z.string().min(6, 'Please enter the complete 6-digit verification code or recovery key'),
  remember_device: z.boolean().optional(),
});

type TwoFactorFormValues = z.infer<typeof twoFactorSchema>;

function TwoFactorContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const dispatch = useAppDispatch();

  const [isLoading, setIsLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [useRecoveryCode, setUseRecoveryCode] = useState(false);
  const [resendTimer, setResendTimer] = useState(30);

  const {
    register,
    handleSubmit,
    setValue,
    formState: { errors },
  } = useForm<TwoFactorFormValues>({
    resolver: zodResolver(twoFactorSchema),
    defaultValues: {
      remember_device: true,
    },
  });

  useEffect(() => {
    let timer: NodeJS.Timeout;
    if (resendTimer > 0) {
      timer = setTimeout(() => setResendTimer((prev) => prev - 1), 1000);
    }
    return () => clearTimeout(timer);
  }, [resendTimer]);

  const onSubmit = async (data: TwoFactorFormValues) => {
    setIsLoading(true);
    setErrorMsg(null);
    try {
      const { tokens, user } = await authService.verify2FA({
        code: data.code.trim(),
        remember_device: data.remember_device,
        recovery_code: useRecoveryCode,
      });

      dispatch(
        setCredentials({
          user,
          access_token: tokens.access_token,
          refresh_token: tokens.refresh_token,
        })
      );

      const redirectUrl = searchParams.get('redirect') || '/studio';
      router.push(redirectUrl);
    } catch (err: any) {
      const detail = err.response?.data?.detail;
      setErrorMsg(
        detail ||
          (useRecoveryCode
            ? 'Invalid recovery code. Each backup code can only be used once.'
            : 'Invalid authentication code. Please verify the 6-digit number in your authenticator app.')
      );
    } finally {
      setIsLoading(false);
    }
  };

  const handleResend = () => {
    if (resendTimer > 0) return;
    setResendTimer(60);
    // Trigger SMS/Email push fallback if configured
  };

  return (
    <GuestGuard>
      <Card variant="standard" className="p-6 sm:p-8 md:p-10 bg-slate-900/90 border-slate-800 space-y-6 shadow-2xl">
        <div className="space-y-2 text-center sm:text-left">
          <div className="w-12 h-12 rounded-xl bg-indigo-600/20 border border-indigo-500/30 text-indigo-400 flex items-center justify-center mb-3">
            <ShieldCheck className="w-6 h-6" />
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
            {useRecoveryCode ? 'Enter Backup Recovery Code' : 'Two-Factor Verification'}
          </h1>
          <p className="text-xs sm:text-sm text-slate-400 leading-relaxed">
            {useRecoveryCode
              ? 'Enter one of the 10-character emergency recovery codes provided when you configured two-factor authentication.'
              : 'Enter the 6-digit verification code generated by your mobile authenticator app (Google Authenticator, Authy, or Microsoft Authenticator).'}
          </p>
        </div>

        {errorMsg && (
          <AlertBanner type="error" title="Verification Failed">
            {errorMsg}
          </AlertBanner>
        )}

        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <label htmlFor="2fa-code" className="block text-sm font-medium text-slate-200">
                {useRecoveryCode ? 'Backup Recovery Code' : 'Authentication Code'}
              </label>
              <button
                type="button"
                onClick={() => {
                  setUseRecoveryCode(!useRecoveryCode);
                  setValue('code', '');
                  setErrorMsg(null);
                }}
                className="text-xs text-indigo-400 hover:text-indigo-300 font-semibold underline transition-colors focus-ring rounded"
              >
                {useRecoveryCode ? 'Use 6-Digit App Code' : 'Use Backup Recovery Code'}
              </button>
            </div>

            <Input
              id="2fa-code"
              type="text"
              placeholder={useRecoveryCode ? 'e.g. SB-8923-4410' : '• • • • • •'}
              maxLength={useRecoveryCode ? 16 : 8}
              icon={<KeyRound className="w-4 h-4" />}
              error={errors.code?.message}
              disabled={isLoading}
              className="text-center font-mono text-lg tracking-[0.25em] font-bold"
              {...register('code')}
            />
          </div>

          <div className="flex items-center gap-2.5 pt-1">
            <input
              id="remember_device"
              type="checkbox"
              className="w-4 h-4 rounded bg-slate-950 border-slate-700 text-indigo-600 focus:ring-indigo-500 focus:ring-offset-slate-950 transition-colors cursor-pointer"
              disabled={isLoading}
              {...register('remember_device')}
            />
            <label htmlFor="remember_device" className="text-xs text-slate-300 select-none cursor-pointer">
              Trust this device for 30 days (`no 2FA prompt on return`)
            </label>
          </div>

          <Button
            type="submit"
            variant="gradient"
            size="lg"
            className="w-full font-bold mt-2 min-h-[46px]"
            isLoading={isLoading}
          >
            Verify &amp; Enter AI Studio
          </Button>
        </form>

        {!useRecoveryCode && (
          <div className="pt-2 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-slate-400 border-t border-slate-800/80 pt-4">
            <button
              type="button"
              onClick={handleResend}
              disabled={resendTimer > 0}
              className="inline-flex items-center gap-1.5 text-indigo-400 hover:text-indigo-300 font-semibold disabled:text-slate-500 transition-colors focus-ring rounded p-1"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${resendTimer > 0 ? 'animate-spin' : ''}`} />
              <span>{resendTimer > 0 ? `Resend code in ${resendTimer}s` : 'Resend verification code'}</span>
            </button>

            <Link
              href="/login"
              className="inline-flex items-center gap-1 text-slate-400 hover:text-white transition-colors"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              <span>Return to Sign In</span>
            </Link>
          </div>
        )}
      </Card>
    </GuestGuard>
  );
}

export default function TwoFactorPage() {
  return (
    <React.Suspense fallback={<div className="min-h-screen bg-slate-950 flex items-center justify-center text-slate-400">Loading two-factor verification...</div>}>
      <TwoFactorContent />
    </React.Suspense>
  );
}
